### ISSUE TITLE
Implement standardised response paging in API

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#14]
- Investigate if a standard exist
- Implement it

E.g. see PDOK WFS response paging:
http://pdok-ngr.readthedocs.io/handleidingen.html#wfs-2-0-responsepaging

**Comment by ndkv** [comment]
Have a look at Digitaal Stelsel Omgevingswet API doc: https://forum.pdok.nl/t/nieuwe-api-strategie/685  

They've adopted JSON+HAL (Hypertext Application Language), see page 29. The pagination links are returned in the JSON response under the `links` key. Pagination itself is controlled by query parameters, though. 

<img width="691" alt="screenshot 2018-03-26 12 27 11" src="https://user-images.githubusercontent.com/778666/37901350-3a832b4c-30f1-11e8-9a7b-35a6c488de48.png">

**Comment by zoot-wur** [comment]
Same as @ndkv ? https://brk.basisregistraties.overheid.nl/restful-api?articleid=1930301#/paths/~1perceel/get as example/template

**Comment by yke** [comment]
has been done using page_size, page
