### ISSUE TITLE
Option to request data as shape file

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#17]

**Comment by robknapen** [comment]
Might not have to be a Shapefile. Users are looking for an option to download lots of data from the Cube so that e.g. a map of the Netherlands can be visualised.

**Comment by yke** [comment]
Geopackage ?

**Comment by yke** [comment]
Added to WENR GITLAB  (https://git.wur.nl/rande001/AgroDataCubeAdapter/-/issues/275)
