### ISSUE TITLE
AgroDataCube Sprint default token has expired

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#2]
The default token used during the AgroDataCube Sprint has expired. Requests now return this message:

This token is expired,
please request a new token !

**Comment by robknapen** [comment]
Has been fixed with an extended temporary default token. Will be replaced in due time with the official registration procedure and method for requesting tokens.

**Comment by yke** [comment]
Due to some miscommunication all tokens usesd for the sprint expired on Saturday march 17th at 00 hrs.  

Solved.
