### ISSUE TITLE
Add groundwater regime data (grondwatertrappen) from Dutch soil map

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#21]

**Comment by robknapen** [comment]
For info (in Dutch) see: https://nl.wikipedia.org/wiki/Grondwatertrap

This data is available from the Dutch soil map (it is part of the soil codes).

**Comment by yke** [comment]
even met Folkert opnemen welke kaart dat is en of die publiek is. Daarnasst zijn er ook andere Gt kaarten.

**Comment by yke** [comment]
No longer in soil map we need separate map.
