### ISSUE TITLE
Add access to Dutch 'boorprofielen' (part of the BRO) from the Cube API

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#22]

**Comment by yke** [comment]
Model kiezen (BIS of BRO), ik denk BRO en dan kijken hoe te ontsluiten (master detail etc).

**Comment by yke** [comment]
available in V2 (curl -X GET "https://agrodatacube-test.wenr.wur.nl/api/v2/rest/bis/pfb?pfb_id=936") also see

**Comment by yke** [comment]
available in V2 (curl -X GET "https://agrodatacube-test.wenr.wur.nl/api/v2/rest/bis/pfb?pfb_id=936") also see
