### ISSUE TITLE
Implement vector tiles (for some datasets)

### ISSUE THREAD

**Issue by ndkv** [AgroDataCube/api-v1#25]
Displaying data in a basemap-like manner with the REST API is a bit cumbersome and wasteful. 

A tiling service will make life easier and more pleasant. Since it's 2018 one might consider vector tiles. 😃 An initial beta implementation can be static: PostGIS -> GeoJSON -> `tippencanoe` -> tiles as mentioned here: https://forum.pdok.nl/t/vector-tiles-brt-en-bgt-via-pdok/1103/15. Apparently QGIS can read vector tiles as well maing the implementation of WMS/TMS obsolete.

If the process proves computationally/storage intensive one might decide to implement it for a limited number of datasets e.g. those prone to being displayed as basemaps.

**Comment by yke** [comment]
added

**Comment by yke** [comment]
Added to WENR GITLAB https://git.wur.nl/rande001/AgroDataCubeAdapter/-/issues/273
