### ISSUE TITLE
Include a couple of step-by-step recipes for retrieving (linked) datasets

### ISSUE THREAD

**Issue by ndkv** [AgroDataCube/api-v1#26]
The Postman docs provide a great overview of the API's full capabilities and extent. They can, however, be a bit overwhelming for first time users especially when retrieving (linked) data from several endpoints. 

A useful addition to the docs could be a number of step-by-ste recipes that show how to filter and get linked (on e.g. field ID) data from  endpoints e.g. show how to perform a spatial lookups to get a collection of field IDs and use those to get more information about each. 

The recipes automatically double as an exposé of the datasets and a demonstration of the API's capabilities.

**Comment by robknapen** [comment]
The docs are currently managed in a Postman online collaboration workspace. If you have a Postman account and I can try to add you so that you can add stuff.

**Comment by zoot-wur** [comment]
Show how data related to each other and what a possible flow of getting data could be. implement in multiviewer.

**Comment by zoot-wur** [comment]
image showing data relations (first attempt) has been aded to the code.

**Comment by robknapen** [comment]
Marked as done, so closing the issue.
