### ISSUE TITLE
Geometries use too many digits, beyond actual coordinate accuracy 

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#3]
Geometry coordinates in a request response are represented with digits beyond the actual accuracy. E.g. in RD coordinates:

```
"type": "MultiPolygon",
"coordinates": [[[
  [ 178640.6094, 450410.781199999],
  [ 178634.4844, 450410.281199999],
```

Better to limit them to the real known precision.

**Comment by yke** [comment]
This is how they are received from Postgis. We can see waht we can do but seems a low priority issue.

**Comment by robknapen** [comment]
Perhaps set the number digits for the output in the st_asgeojson function?

https://postgis.net/docs/ST_AsGeoJSON.html

**Comment by yke** [comment]
Add nr of decimals to st_asgeojson fixed it.
