### ISSUE TITLE
'Datum' property of meteodata resource is wrongly named and formatted

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#31]
For example the request ```https://agrodatacube.wur.nl/api/v1/rest/meteodata``` currently returns data like this:

```
"features": [
{
  "type": "Feature",  
  "geometry": null,
  "properties": {
    "meteostationid": 210,
    "datum": 19510101,
    "mean_temperature": 1.5,
    "min_temperature": -0.9,
    "max_temperature": 4.2,
    "mean_sea_level_pressure": 988.2,
    "mean_daily_cloud_cover": 7.0
  }
},
```

In this, the property 'datum' should be called 'date', and it's value should be properly formatted as a date type (not as a number).

**Comment by yke** [comment]
Probably jdbc driver returns timestamp type.

**Comment by yke** [comment]
Date format was defined as yyyyMMdd changed to yyyy-MM-dd.
