### ISSUE TITLE
Real-time update of NDVI data in the Cube from GroenMonitor.nl

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#32]
Implement an automated update procedure to get the latest NDVI data from GroenMonitor.nl into the AgroDataCube. Currently updating is done manually.

**Comment by yke** [comment]
Geotiffs or wouters procedure ?

**Comment by robknapen** [comment]
Preferably the 'rawest' data that GroenMonitor.nl can deliver. (1) pre-processed multiband geotiffs, (2) pre-calculated NDVI singleband geotiff, (3) pre-calculated NDVI zonal stats per field.

**Comment by yke** [comment]
Realized today
