### ISSUE TITLE
'Grasland natuurlijk' and 'Grasland, natuurlijk' have different crop codes (1905, 3718)

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#34]

**Comment by yke** [comment]
agrodatacube=> select distinct crop_code, crop_name from gewaspercelen where crop_code in ('1905','3718');
 crop_code |      crop_name
-----------+----------------------
 3718      | Grasland, natuurlijk
 1905      | Grasland natuurlijk

**Comment by yke** [comment]
Grasland in crop information (gebaseerd op alle gewaspercelen)

agrodatacube=> select distinct cropcode, cropname from cropinformation where cropcode in ('1905','3708') or lower(cropname) like '%natuurlijk%';
 cropcode |                                                     cropname
| ---------- | ---------------------------------- |
| 1563     | Grasland, natuurlijk, minder dan 50% van de oppervlakte bedekt |
| 1564     | Grasland, natuurlijk, voor 50-75% van de oppervlakte bedekt |
| 1905     | Grasland natuurlijk |
| 2301     | Natuurlijk grasland met hoofdfunctie landbouw |
| 2302     | Natuurlijk grasland (begraasd) met beperkte landbouwact. |
|| 270      | Grasland, natuurlijk (max. 5 ton drogestof per ha.), tenmins |
| 331      | Grasland, natuurlijk. Hoofdfunctie landbouw. |
| 332      | Grasland, natuurlijk. Hoofdfunctie natuur. |
 336      | Grasland, natuurlijk. Areaal met een natuurbeheertype dat overwegend voor landbouwactiviteiten-GLB wordt gebruikt |
 3718     | Grasland, natuurlijk
