### ISSUE TITLE
Crop code 265 'Blijvend grasland' is not in the list

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#35]

**Comment by yke** [comment]
```sql
agrodatacube=> select distinct cropcode, cropname from cropinformation where cropcode='265';
```

| cropcode |      cropname |
| ---------- | -------------------- |
| 265      | Grasland, blijvend |

(1 row)

**Comment by yke** [comment]
Mail aan : Os, Jaap van; GeoDesk-WUR	

Subject : RVO en data	

Heren

Ik heb de gewaspercelen van rvo van de afgelopen 6 jaar geladen (meeste heb ik via Rob Smidt gekregen, nog bedankt). Wat echt opvalt is de dynamiek in de gewascodes en hu omschrijvingen.

Bv alles met een omschrijving die ‘naruurlijk’ bevat.

cropcode |                                                     cropname
----------+-------------------------------------------------------------------------------------------------------------------
1563     | Grasland, natuurlijk, minder dan 50% van de oppervlakte bedekt
1564     | Grasland, natuurlijk, voor 50-75% van de oppervlakte bedekt
1905     | Grasland natuurlijk
2301     | Natuurlijk grasland met hoofdfunctie landbouw
2302     | Natuurlijk grasland (begraasd) met beperkte landbouwact.
270      | Grasland, natuurlijk (max. 5 ton drogestof per ha.), tenmins
331      | Grasland, natuurlijk. Hoofdfunctie landbouw.
332      | Grasland, natuurlijk. Hoofdfunctie natuur.
336      | Grasland, natuurlijk. Areaal met een natuurbeheertype dat overwegend voor landbouwactiviteiten-GLB wordt gebruikt
3718     | Grasland, natuurlijk
(10 rows)

Dit is natuurlijk van de zotte en je kunt hier ook niets mee is 1564 wel/niet natuurlijkgrasland of valt het onder braak ?. 

Bij mais heb je dit ook maar dan ook nog eens onderscheid tussen “Maïs snij”, “Maïs, snij”, “Mais snij” etc. 

Zou iemand een keer bij RVO kunnen aankaarten dat ze dit op een normale manier regelen en bruikbaar maken. Bv bij 1564 wat is die andere 25 – 50 % dan , dat is een flink deel van het perceel bijna de helft.

**Comment by yke** [comment]
Ook gevonden

Bron      | year | crop_code |          crop_name
---------- | ------ | ----------- | -----------------------------
        1 | 2012 | 246       | Karwijzaad (oogst 2002)
        1 | 2013 | 246       | Karwijzaad (oogst 2002)
        1 | 2014 | 246       | Karwijzaad (oogst dit jaar)
        2 | 2002 | 246       | Karwijzaad (oogst dit jaar)
        1 | 2016 | 246       | Karwijzaad (oogst dit jaar)
        1 | 2017 | 246       | Karwijzaad (oogst dit jaar)
        1 | 2015 | 246       | Karwijzaad (oogst dit jaar)
(7 rows)

**Comment by yke** [comment]
En nog een

| Bron | crop_code |                          crop_name |
| ---------- | ----------- | -----------------------
|        1 | 1926      | Aardappelen, poot op klei, uitgroeiteelt (loofver na 15-08)
|        1 | 1926      | Agrarisch natuurmengsel
|        2 | 1926      | Agrarisch natuurmengsel

(3 rows)

**Comment by zoot-wur** [comment]
Closed to prevent this issue from evolving to a discussion.
