### ISSUE TITLE
Add more sub-field data (AHN, NDVI, soil)

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#36]
Add requests so that sub-field data can be retrieved from the Cube. Mostly this will be a cutout of the raster data given the geometry of the field, and return the raster either as a GeoTiff (spatially referenced), a png/jpg image, or a data matrix in (geo)json.

We should at least add sub-field height data (AHN2/3) and sub-field NDVI data (based on rasters from GroenMonitor.nl). We can also add sub-field soil data.

**Comment by robknapen** [comment]
See also issue #52.

**Comment by yke** [comment]
Solved in V2

**Comment by yke** [comment]
Solved in V2
