### ISSUE TITLE
Add NDWI (normalised difference water index) data

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#37]
NDWI can be calculated from multiband Sentinel 2 data.

**Comment by yke** [comment]
Les first discuss whether we want images or data agrregated/summerized to field level.

**Comment by robknapen** [comment]
As discussed, sub-field raster data.

**Comment by yke** [comment]
See https://git.wur.nl/rande001/AgroDataCubeAdapter/-/issues/259 so we will work on this.

**Comment by yke** [comment]
See https://git.wur.nl/rande001/AgroDataCubeAdapter/-/issues/259 so we will work on this.
