### ISSUE TITLE
Create a sample database (subset of the Cube) for development and testing

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#38]
aka Duckburg

**Comment by yke** [comment]
Center of Wagenignen is 51.9648787,5.6627568. Take a box 10km square around this for field selection.

**Comment by zoot-wur** [comment]
sample database (aka 'Duckburg', see https://en.wikipedia.org/wiki/Donald_Duck_universe#Duckburg) is available (_adctest.dmp.txt_). Ask us!

steps to use (postgres 9.4):
1.  create database **adctest**, owner adctest;
2.  create extension postgis;
3.  psql --host localhost --port 5432 --username "postgres" --dbname "adctest" -v ON_ERROR_STOP=1 < adctest.dmp.txt

**Comment by zoot-wur** [comment]
database is available, verified and stept to use are documented here and in readme.

**Comment by zoot-wur** [comment]
database is available, verified and stept to use are documented here and in readme.
