### ISSUE TITLE
page_offset seems to be offset in number of items, not number of pages

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#39]
I think page_offset means the offset in number of pages, given the page_size. So with page_size = 5, page_offset = 0 should mean get the first 5 items (1..5). page_offset = 1 should get the next 5 items (6..10), etc. The final bunch might have less items than the page_size, or 0 items.

Currently page_offset seems to mean the item number to start returning results from. I.e. item_offset, instead of page_offset.

**Comment by zoot-wur** [comment]
Please inform everyone when making such a change to a 'feature'.

**Comment by robknapen** [comment]
Seems that this has been changed meanwhile. The page_offset parameter now counts in number of pages (given the page_size), and not in number of items.
