### ISSUE TITLE
RFC/Wish: allow own field geometry to be used as predefined fields

### ISSUE THREAD

**Issue by zoot-wur** [AgroDataCube/api-v1#40]
2018 fields are not yet available in ADC. using the geomtry to retrieve e.g. soil information returns the full class item geometries without clipping.  Having a choice for clipped geometries is welcomed!

**Comment by robknapen** [comment]
When BRP 2018 will be made available as downloadable file, we will add it to the cube.

A request like: ```https://agrodatacube.wur.nl/api/v1/rest/soiltypes?output_epsg=28992&geometry=POLYGON((%20164685%20451073,%20184119%20451073,%20184119%20433332,%20164685%20433332,%20164685%20451073%20))&epsg=28992&page_size=25&page_offset=0``` is already possible. So you want a parameter added that controls if clipped or complete soil geometries found are returned?

**Comment by yke** [comment]
seesm to be solved
