### ISSUE TITLE
Inconsistent types used for property soilparamid in requests

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#41]
Het request: ```http://agrodatacube.wur.nl/api/v1/rest/fields/1/soilparams``` geeft in de properties een soilparamid van type String terug. Maar bijvoorbeeld het request: ```http://agrodatacube.wur.nl/api/v1/rest/soilparams/303``` gebruikt een integer type voor soilparamid.

**Comment by yke** [comment]
In de db is het een string omdat dat in het oorspronkelijke bestand zo is (of dat een bewuste keuze is is niet aangegeven). Conversie naar integer zou dus wel kunnen maar dan is ern kans op problemen bij volgende versie.

Overigens resources hebben volgens mij geen type denk aan ?crop_name=mais

**Comment by zoot-wur** [comment]
...return type testen in geojson formatter

**Comment by yke** [comment]
In the db the type of soilparamid is a numeric(10,0), when being accessed from the JDBC resultset the type is a BIGDecimal not integer or float.

Changed formatters

*  date values are formatted
*  string values are enclosed in "
*  all others are added as "name" : value.
