### ISSUE TITLE
Send response status 401 Unauthorized when token is expired or reached limits 

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#43]
Currently when no token, an invalid or expired token, or a token with exceeded limits, is send in the request the server responds with a http 500 status (Internal Server Error). A 4xx error such as 401 makes more sense.

**Comment by yke** [comment]
I discussed this last week with Inge. Beside the status 500 also a valid message (json) is returned indicating the problem.  So her suggestion was return a http 200 and a valid message (json) indicating issue. In many cases when a non http 200 code is returned textual results are either unexpected or no accessible.

**Comment by robknapen** [comment]
I would prefer using the standardized http status codes (such as 400, 401, 403, 404) where appropriate.

If we do deviate from that we have to clearly document how we use the http codes and what custom json status messages clients should expect. And maybe make them more machine processable by adding an error code.

**Comment by yke** [comment]
Will not be solved due to existence of V2
