### ISSUE TITLE
Add more sample source codes that demonstrate the use of the API

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#45]
These could come for example from work at the various hackathons. Would be helpful for (other) developers and give them a starting point.

**Comment by zoot-wur** [comment]
see #26

**Comment by robknapen** [comment]
I have added a number of Python notebooks to the api-v1-samples folder too that contain examples of how to work with the AgroDataCube and its data.

**Comment by zoot-wur** [comment]
Sjoerd from Vitens with some help from me developed a machine learning jupyter notebook sample using ADC data. The program itself doesn't have meaningful results but as a demonstrator it is useful.

**Comment by zoot-wur** [comment]
2 more samples are added to api v1 sample project.
