### ISSUE TITLE
URL's too long

### ISSUE THREAD

**Issue by yke** [AgroDataCube/api-v1#48]
In some cases providing a very long URL results in an issue. Its unclear were this problem occurs (browser, erverside etc). An example is the polygon for the Klooster waterwingebied, used in the hackathon at the Marke (may 31st, june 1st).

Possible solutions
* use wkb i.s.o wkt
* do http post i.s.o. get

**Comment by zoot-wur** [comment]
allow post, start with part of the api.

**Comment by yke** [comment]
It is not possible to have the ame method a a post and and a get but there is an extremely simple workaround.

https://stackoverflow.com/questions/17338828/can-i-use-both-post-and-get-on-the-same-method

**Comment by robknapen** [comment]
Documentation needs to be properly updated to reflect this change.

**Comment by robknapen** [comment]
Not completed, moving to next milestone.

**Comment by yke** [comment]
We will take this into account now. Making GET and POST possible.

**Comment by yke** [comment]
V2 enables POST
