### ISSUE TITLE
Add usage examples (with images of maps, graphs) on the AgroDataCube website

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#49]
It would be good to have a few examples of how the (data from) AgroDataCube can be used on the AgroDataCube website. So that non-developers can quickly see what is possible, and why they should promote the AgroDataCube :-)

**Comment by zoot-wur** [comment]
see #26

**Comment by zoot-wur** [comment]
Work on graph and map examples are in progress see #26 and #45.
