### ISSUE TITLE
sorting fields by %overlap on spatial query

### ISSUE THREAD

**Issue by zoot-wur** [AgroDataCube/api-v1#50]
When querying the fields with a geometry the first item returned isn't necessarily the best match in terms of %overlap. Is it possible to specify the type of ordering and have overlap as one of the options?

**Comment by zoot-wur** [comment]
Start with fields. More for next milestone.

**Comment by yke** [comment]
Available for testing

**Comment by zoot-wur** [comment]
working fine now! after solving some hick-ups...

**Comment by robknapen** [comment]
Marked as done, closing the issue.
