### ISSUE TITLE
add (meteostation) id as path variable

### ISSUE THREAD

**Issue by zoot-wur** [AgroDataCube/api-v1#54]
meteostationid and possibly others (?) should be available as path variable as fieldid is.

**Comment by yke** [comment]
It is available in https://agrodatacube.wur.nl/api/v1/rest/meteodata/391/2017 where else do you want it

**Comment by zoot-wur** [comment]
however https://agrodatacube.wur.nl/api/v1/rest/meteodata/391 is not.

**Comment by yke** [comment]
Done in V2
