### ISSUE TITLE
request for soilcode with forward slash

### ISSUE THREAD

**Issue by zoot-wur** [AgroDataCube/api-v1#56]
soilcode can contain forward slashes, e.g. aVz/vWz/pZn21 (8327) The request using this code fails.

**Comment by yke** [comment]
Encode them ?

**Comment by zoot-wur** [comment]
Double encoding is needed: 
soilcode: aVz/vWz/pZn21
encode /: aVz%2FvWz%2FpZn21
encode whole uri: aVz%252FvWz%252FpZn21

Solved but needs documentation!

**Comment by yke** [comment]
No solution at this moment. Added to WENR GIT
