### ISSUE TITLE
Token usage status request fixes

### ISSUE THREAD

**Issue by robknapen** [AgroDataCube/api-v1#61]
The new request (api/v1/rest/status) to retrieve token usage status can use two improvements:

1. It works without including a token in the header. In that case it returns valid json with status ok but empty usage info. Better to return the "token required" message, like many other API requests do.
2. The request returns the internal SQL query used, such details need (should) not be surfaced to the end users. Remove the field from the response json please.

**Comment by yke** [comment]
Changed in V2
